name: Build and publish to pages
on:
  push:
    branches:
      - pages
      - pages-test
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build and publish to pages
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'renyuneyun'
        reponame: 'PermiX'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
